### PR TITLE
Fix errors in the engine

### PR DESCRIPTION
**Pull request by DrSmugleaf**

### CODE REVIEW

**Review by Clyybber — APPROVED** [review]
:heck:

**Review by gradientvera — APPROVED** [review]
I 100 % manually reviewed the 754 files in this PR and they're totally fine yes.

**Review by AJCM-git — APPROVED** [review]
amo

**Review by gradientvera — APPROVED** [review]
gus

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Review by AJCM-git — APPROVED** [review]

**Comment by PaulRitter** [comment]
good second pr

**Pull request merged**
